
Summary: OSG tools for querying and debugging glideinWMS
Name: kestrel
Version: 0.1
Release: 1
# Tarball generated by:
# python setup.py sdist
#
Source0: %{name}-%{version}.tar.gz
License: Apache 2.0
Group: Development/Libraries
BuildRoot: %{_tmppath}/%{name}-%{version}-%{release}-buildroot
Prefix: %{_prefix}
BuildArch: noarch
Vendor: Brian Bockelman <bbockelm@cse.unl.edu>

%description
%{summary}

%prep
%setup -n %{name}-%{version}

%build
python setup.py build

%install
python setup.py install -O1 --root=$RPM_BUILD_ROOT --record=INSTALLED_FILES

%clean
rm -rf $RPM_BUILD_ROOT

%files -f INSTALLED_FILES
%defattr(-,root,root)

%config(noreplace) %{_sysconfdir}/kestrel/kestrel_config
%config(noreplace) %{_sysconfdir}/kestrel/config.d/01-osg.conf

%changelog
* Tue Jan 20 2015 Brian Bockelman <bbockelm@cse.unl.edu> - 0.1-1
- Initial toolset release.


