#!/bin/sh

if [ -a /usr/share/kestrel/kestrel_config_global ]; then
  export CONDOR_CONFIG=/usr/share/kestrel/kestrel_config_global
fi

if [ "X$KESTREL_CONFIG" != "X" ]; then
  export CONDOR_CONFIG=$KESTREL_CONFIG
fi

FORMAT_FILE=`basename -- $0`

if [ -a /usr/share/kestrel/$FORMAT_FILE.cpf ]; then
  PRINT_FORMAT=/usr/share/kestrel/$FORMAT_FILE.cpf
else
  ROOTDIR=`dirname $0`
  if [ -a $ROOTDIR/$FORMAT_FILE.cpf ]; then
    PRINT_FORMAT=$ROOTDIR/$FORMAT_FILE.cpf
  else
    LIBEXEC=`condor_config_val KESTREL_SHARE 2>/dev/null`
    if [ "X$KESTREL_SHARE" != "X" -a -a $KESTREL_SHARE/$FORMAT_FILE.cpf ]; then
      PRINT_FORMAT=$KESTREL_SHARE/$FORMAT_FILE.cpf
    else
      echo "Unable to find the Kestrel install directories. 1>&2"
      exit 1
    fi
  fi
fi

exec condor_status -any -pr $PRINT_FORMAT "$@"

